name: BuildDocumentation

run-name: Build documentation

on:
  pull_request:
    branches:
      - deployment

  push:
    branches:
      - Esercizi-FrancescoTurini

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dalibo/pandocker:stable


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: List submodules
        run: git submodule status

      - name: Check Python version
        run: python --version 
           
      - name: Install dependencies
        run: |
          cd Esercizi/BicoccaCoursePython2024
          pip install --break-system-packages -e .
          cd docs
          pip install --break-system-packages -r requirements_sphinx.txt


      - name: Build the documentation
        run: |
          cd Esercizi/BicoccaCoursePython2024/docs
          ln -s ../../SolvedExercises SolvedExercises
          sphinx-build -b html . _build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: Esercizi/BicoccaCoursePython2024/docs/_build/html  # Indicate the dicrectory for the publishing
          publish_branch: gh-pages  # Destination Branch for GitHub pages
          force_orphan: true
