name: BuildDocumentation

run-name: Build documentation

on:
  pull_request:
    branches:
      - deployment
  workflow_dispatch:

  push:
    branches:
      - Esercizi-FrancescoTurini

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dalibo/pandocker:stable


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check Python version
        run: python --version 
           
      - name: Install dependencies
        run: |
          cd Esercizi/BicoccaCoursePython2024
          pip install --no-cache-dir -e .
          pip install --no-cache-dir sphinx sphinx_rtd_theme nbsphinx


      - name: Build the documentation
        run: |
          cd Esercizi/BicoccaCoursePython2024
          cd docs
          ln -s ../../SolvedExercises SolvedExercises
          sphinx-build -b html . _build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: Esercizi/BicoccaCoursePython2024/docs/_build/html  # Indicate the dicrectory for the publishing
          publish_branch: gh-pages  # Destination Branch for GitHub pages
          force_orphan: true
