name: Deploy_to_Test_PyPI

on:
    pull_request:
        branches:
            - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
       python-version: "3.11.9" 



    - name: Install dependencies
      run: |
        cd Esercizi/BicoccaCoursePython2024
        pip install -e .
        pip install build twine

    - name: Build the distribution
      run: |
        cd Esercizi/BicoccaCoursePython2024
        python -m build

    - name: Deploy to Test PyPI
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        cd Esercizi/BicoccaCoursePython2024
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*


