name: Test Lezione8
run-name: Test on BicoccaCoursePython2024
on:
  push:
    branches:
      - main
      - Esercizi-FrancescoTurini
  pull_request:
    branches:
      - main

jobs:
  TestBicoccaCoursePython2024:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9" # Adjust the Python version as needed

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy
            
      - name: Install BicoccaCoursePython2024
        run: |
          cd Esercizi/BicoccaCoursePython2024
          pip install -e .
          cd ../..

      - name: Run pytest on BicoccaCoursePython2024
        run: pytest Esercizi/BicoccaCoursePython2024
