name: Test Lezione8
run-name: Test on MyPackage
on:
  push:
    branches:
      - main
      - Esercizi-FrancescoTurini
  pull_request:
    branches:
      - main

jobs:
  TestMyPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9" # Adjust the Python version as needed

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest on MyPackage
        run: pytest Esercizi/MyPackage
